name: rheology
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - appmode
  - ipympl
  - jupyter
  - lmfit
  - matplotlib
  - numpy
  - pip
  - python-dateutil
  - scipy
  - setuptools
  - widgetsnbextension
  - xlrd
  - zlib
  - pandas
  - pymongo
  - pybroom
  - seaborn
  - boto3
  - pillow
  - pims
  - trackpy
  - jupyter_contrib_nbextensions
  - pivottablejs
  - pybroom
  - pymongo
  - jupyter_contrib_nbextensions
  - pip:
    - ipyupload
    - xmltodict
    - emcee
    - corner